version: '3.8'

services:
  web:
    build: .
    command: gunicorn ifuptime.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306" # Expose MySQL port for external access

  redis:
    image: redis:latest
    ports:
      - "6379:6379" # Expose Redis port for external access

  celery_worker:
    build: .
    command: celery -A ifuptime worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - MONITORING_NODE_NAME=${MONITORING_NODE_NAME}
      - MONITORING_NODE_LOCATION=${MONITORING_NODE_LOCATION}
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    command: celery -A ifuptime beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - MONITORING_NODE_NAME=${MONITORING_NODE_NAME}
      - MONITORING_NODE_LOCATION=${MONITORING_NODE_LOCATION}
    depends_on:
      - db
      - redis

volumes:
  db_data: