# Generated by Django 4.2.23 on 2025-06-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for this monitoring node (e.g., Shanghai-Node-01)', max_length=255, unique=True)),
                ('location', models.CharField(blank=True, help_text='Geographical location of this node (e.g., Shanghai, Tokyo)', max_length=255, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='Timestamp of the last successful heartbeat from this node.', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Indicates if the node is currently considered active.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the node.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='monitorlog',
            name='node_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
