# Generated by Django 4.2.23 on 2025-06-27 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_user_is_send_daily_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='SslMonitor',
            fields=[
                ('monitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='monitoring.monitor')),
            ],
        ),
        migrations.AddField(
            model_name='monitorlog',
            name='ssl_days_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorlog',
            name='ssl_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorlog',
            name='ssl_valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='monitor_type',
            field=models.CharField(choices=[('http', 'HTTP(s)存活检测'), ('keyword', '关键字检测'), ('api', 'API检测'), ('ssl', 'SSL证书检测')], max_length=10),
        ),
    ]
