# Generated by Django 4.2.23 on 2025-06-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_sslmonitor_monitorlog_ssl_days_remaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='frequency',
            field=models.PositiveIntegerField(choices=[(300, '5 minutes'), (3600, '1 hour'), (43200, '12 hours'), (86400, '24 hours')], default=300),
        ),
    ]
